<div class="block" >
<?php 
echo __('User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities
        User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities User Rules and Responsibilities');
?>
</div>